#pragma once

// v1.3.13
#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 3
#define APP_VERSION_PATCH 13
#define APP_VERSION_BUILD 0

#define APP_VERSION_STR_HELPER(x) #x
#define APP_VERSION_STR_VALUE(x) APP_VERSION_STR_HELPER(x)
#define APP_VERSION_WIDE_HELPER(x) L##x
#define APP_VERSION_WIDE_VALUE(x) APP_VERSION_WIDE_HELPER(x)

#define APP_VERSION_STR                      \
    APP_VERSION_STR_VALUE(APP_VERSION_MAJOR) \
    "." APP_VERSION_STR_VALUE(APP_VERSION_MINOR) "." APP_VERSION_STR_VALUE(APP_VERSION_PATCH)

#define APP_VERSION_STR_FULL APP_VERSION_STR "." APP_VERSION_STR_VALUE(APP_VERSION_BUILD)
#define APP_VERSION_WSTR APP_VERSION_WIDE_VALUE(APP_VERSION_STR)

constexpr wchar_t kAppVersion[] = L"v" APP_VERSION_WSTR;
